/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
*/

#ifndef _mulle_scion_include_private_h__
#define _mulle_scion_include_private_h__

# include <zlib/zlib.h>   // zlib

#endif
