      { @selector( Hoedown), @selector( MulleScionPrinting) },      // fbfc4833;Hoedown;4ef670bb;MulleScionPrinting
      { @selector( Hoedown), MULLE_OBJC_NO_CATEGORYID },      // fbfc4833;Hoedown;;
      { @selector( MulleMutableLineNumber), MULLE_OBJC_NO_CATEGORYID },      // f0a19f70;MulleMutableLineNumber;;
      { @selector( MulleScionAnd), @selector( Printing) },      // e3dc9432;MulleScionAnd;11e5c20c;Printing
      { @selector( MulleScionAnd), MULLE_OBJC_NO_CATEGORYID },      // e3dc9432;MulleScionAnd;;
      { @selector( MulleScionArray), @selector( Printing) },      // 66676032;MulleScionArray;11e5c20c;Printing
      { @selector( MulleScionArray), @selector( TraceDescription) },      // 66676032;MulleScionArray;35e2b50e;TraceDescription
      { @selector( MulleScionArray), @selector( VariableSubstitution) },      // 66676032;MulleScionArray;e459bb08;VariableSubstitution
      { @selector( MulleScionArray), MULLE_OBJC_NO_CATEGORYID },      // 66676032;MulleScionArray;;
      { @selector( MulleScionAssignmentExpression), @selector( NSCoding) },      // 787ae514;MulleScionAssignmentExpression;b67e77cf;NSCoding
      { @selector( MulleScionAssignmentExpression), @selector( Printing) },      // 787ae514;MulleScionAssignmentExpression;11e5c20c;Printing
      { @selector( MulleScionAssignmentExpression), @selector( VariableSubstitution) },      // 787ae514;MulleScionAssignmentExpression;e459bb08;VariableSubstitution
      { @selector( MulleScionAssignmentExpression), MULLE_OBJC_NO_CATEGORYID },      // 787ae514;MulleScionAssignmentExpression;;
      { @selector( MulleScionBinaryOperatorExpression), @selector( NSCoding) },      // 7f708e55;MulleScionBinaryOperatorExpression;b67e77cf;NSCoding
      { @selector( MulleScionBinaryOperatorExpression), @selector( TraceDescription) },      // 7f708e55;MulleScionBinaryOperatorExpression;35e2b50e;TraceDescription
      { @selector( MulleScionBinaryOperatorExpression), @selector( VariableSubstitution) },      // 7f708e55;MulleScionBinaryOperatorExpression;e459bb08;VariableSubstitution
      { @selector( MulleScionBinaryOperatorExpression), MULLE_OBJC_NO_CATEGORYID },      // 7f708e55;MulleScionBinaryOperatorExpression;;
      { @selector( MulleScionBlock), @selector( Debug) },      // 45172873;MulleScionBlock;a6103382;Debug
      { @selector( MulleScionBlock), @selector( NSCoding) },      // 45172873;MulleScionBlock;b67e77cf;NSCoding
      { @selector( MulleScionBlock), @selector( Printing) },      // 45172873;MulleScionBlock;11e5c20c;Printing
      { @selector( MulleScionBlock), MULLE_OBJC_NO_CATEGORYID },      // 45172873;MulleScionBlock;;
      { @selector( MulleScionCommand), @selector( Printing) },      // 4e39ca3d;MulleScionCommand;11e5c20c;Printing
      { @selector( MulleScionCommand), @selector( TraceDescription) },      // 4e39ca3d;MulleScionCommand;35e2b50e;TraceDescription
      { @selector( MulleScionCommand), MULLE_OBJC_NO_CATEGORYID },      // 4e39ca3d;MulleScionCommand;;
      { @selector( MulleScionComparison), @selector( NSCoding) },      // 49a3663b;MulleScionComparison;b67e77cf;NSCoding
      { @selector( MulleScionComparison), @selector( Printing) },      // 49a3663b;MulleScionComparison;11e5c20c;Printing
      { @selector( MulleScionComparison), MULLE_OBJC_NO_CATEGORYID },      // 49a3663b;MulleScionComparison;;
      { @selector( MulleScionConditional), @selector( NSCoding) },      // 3aa237a3;MulleScionConditional;b67e77cf;NSCoding
      { @selector( MulleScionConditional), @selector( Printing) },      // 3aa237a3;MulleScionConditional;11e5c20c;Printing
      { @selector( MulleScionConditional), @selector( TraceDescription) },      // 3aa237a3;MulleScionConditional;35e2b50e;TraceDescription
      { @selector( MulleScionConditional), @selector( VariableSubstitution) },      // 3aa237a3;MulleScionConditional;e459bb08;VariableSubstitution
      { @selector( MulleScionConditional), MULLE_OBJC_NO_CATEGORYID },      // 3aa237a3;MulleScionConditional;;
      { @selector( MulleScionDictionary), @selector( Printing) },      // fc9bd76a;MulleScionDictionary;11e5c20c;Printing
      { @selector( MulleScionDictionary), @selector( TraceDescription) },      // fc9bd76a;MulleScionDictionary;35e2b50e;TraceDescription
      { @selector( MulleScionDictionary), @selector( VariableSubstitution) },      // fc9bd76a;MulleScionDictionary;e459bb08;VariableSubstitution
      { @selector( MulleScionDictionary), MULLE_OBJC_NO_CATEGORYID },      // fc9bd76a;MulleScionDictionary;;
      { @selector( MulleScionDot), @selector( Printing) },      // 7d5c8a96;MulleScionDot;11e5c20c;Printing
      { @selector( MulleScionDot), @selector( VariableSubstitution) },      // 7d5c8a96;MulleScionDot;e459bb08;VariableSubstitution
      { @selector( MulleScionDot), MULLE_OBJC_NO_CATEGORYID },      // 7d5c8a96;MulleScionDot;;
      { @selector( MulleScionElse), MULLE_OBJC_NO_CATEGORYID },      // dd2ccb7a;MulleScionElse;;
      { @selector( MulleScionElseFor), MULLE_OBJC_NO_CATEGORYID },      // 7bc79229;MulleScionElseFor;;
      { @selector( MulleScionEndBlock), @selector( Printing) },      // e7af6406;MulleScionEndBlock;11e5c20c;Printing
      { @selector( MulleScionEndBlock), MULLE_OBJC_NO_CATEGORYID },      // e7af6406;MulleScionEndBlock;;
      { @selector( MulleScionEndFilter), @selector( Printing) },      // 08d3bc90;MulleScionEndFilter;11e5c20c;Printing
      { @selector( MulleScionEndFilter), MULLE_OBJC_NO_CATEGORYID },      // 08d3bc90;MulleScionEndFilter;;
      { @selector( MulleScionEndFor), MULLE_OBJC_NO_CATEGORYID },      // 5111f9a0;MulleScionEndFor;;
      { @selector( MulleScionEndIf), MULLE_OBJC_NO_CATEGORYID },      // 89472bcd;MulleScionEndIf;;
      { @selector( MulleScionEndWhile), MULLE_OBJC_NO_CATEGORYID },      // 2b2dfa05;MulleScionEndWhile;;
      { @selector( MulleScionExpression), @selector( Printing) },      // 5195070c;MulleScionExpression;11e5c20c;Printing
      { @selector( MulleScionExpression), @selector( TraceDescription) },      // 5195070c;MulleScionExpression;35e2b50e;TraceDescription
      { @selector( MulleScionExpression), MULLE_OBJC_NO_CATEGORYID },      // 5195070c;MulleScionExpression;;
      { @selector( MulleScionExpressionCommand), @selector( Debug) },      // 3ebc0794;MulleScionExpressionCommand;a6103382;Debug
      { @selector( MulleScionExpressionCommand), @selector( NSCoding) },      // 3ebc0794;MulleScionExpressionCommand;b67e77cf;NSCoding
      { @selector( MulleScionExpressionCommand), @selector( Printing) },      // 3ebc0794;MulleScionExpressionCommand;11e5c20c;Printing
      { @selector( MulleScionExpressionCommand), @selector( VariableSubstitution) },      // 3ebc0794;MulleScionExpressionCommand;e459bb08;VariableSubstitution
      { @selector( MulleScionExpressionCommand), MULLE_OBJC_NO_CATEGORYID },      // 3ebc0794;MulleScionExpressionCommand;;
      { @selector( MulleScionFilter), @selector( NSCoding) },      // 7e5683c4;MulleScionFilter;b67e77cf;NSCoding
      { @selector( MulleScionFilter), @selector( Printing) },      // 7e5683c4;MulleScionFilter;11e5c20c;Printing
      { @selector( MulleScionFilter), MULLE_OBJC_NO_CATEGORYID },      // 7e5683c4;MulleScionFilter;;
      { @selector( MulleScionFor), @selector( Debug) },      // 875a7f19;MulleScionFor;a6103382;Debug
      { @selector( MulleScionFor), @selector( Printing) },      // 875a7f19;MulleScionFor;11e5c20c;Printing
      { @selector( MulleScionFor), MULLE_OBJC_NO_CATEGORYID },      // 875a7f19;MulleScionFor;;
      { @selector( MulleScionFunction), @selector( NSCoding) },      // f3d6856a;MulleScionFunction;b67e77cf;NSCoding
      { @selector( MulleScionFunction), @selector( Printing) },      // f3d6856a;MulleScionFunction;11e5c20c;Printing
      { @selector( MulleScionFunction), @selector( TraceDescription) },      // f3d6856a;MulleScionFunction;35e2b50e;TraceDescription
      { @selector( MulleScionFunction), @selector( VariableSubstitution) },      // f3d6856a;MulleScionFunction;e459bb08;VariableSubstitution
      { @selector( MulleScionFunction), MULLE_OBJC_NO_CATEGORYID },      // f3d6856a;MulleScionFunction;;
      { @selector( MulleScionFunctionCall), MULLE_OBJC_NO_CATEGORYID },      // f2f45fad;MulleScionFunctionCall;;
      { @selector( MulleScionIdentifierExpression), @selector( VariableSubstitution) },      // a481f37f;MulleScionIdentifierExpression;e459bb08;VariableSubstitution
      { @selector( MulleScionIdentifierExpression), MULLE_OBJC_NO_CATEGORYID },      // a481f37f;MulleScionIdentifierExpression;;
      { @selector( MulleScionIf), @selector( Printing) },      // 4c62315e;MulleScionIf;11e5c20c;Printing
      { @selector( MulleScionIf), MULLE_OBJC_NO_CATEGORYID },      // 4c62315e;MulleScionIf;;
      { @selector( MulleScionIndexing), @selector( Printing) },      // e0291dae;MulleScionIndexing;11e5c20c;Printing
      { @selector( MulleScionIndexing), @selector( TraceDescription) },      // e0291dae;MulleScionIndexing;35e2b50e;TraceDescription
      { @selector( MulleScionIndexing), MULLE_OBJC_NO_CATEGORYID },      // e0291dae;MulleScionIndexing;;
      { @selector( MulleScionLog), @selector( Printing) },      // dbea3c8e;MulleScionLog;11e5c20c;Printing
      { @selector( MulleScionLog), MULLE_OBJC_NO_CATEGORYID },      // dbea3c8e;MulleScionLog;;
      { @selector( MulleScionMacro), @selector( MacroExpansion) },      // 4736d5ed;MulleScionMacro;9ed6e240;MacroExpansion
      { @selector( MulleScionMacro), @selector( NSCoding) },      // 4736d5ed;MulleScionMacro;b67e77cf;NSCoding
      { @selector( MulleScionMacro), MULLE_OBJC_NO_CATEGORYID },      // 4736d5ed;MulleScionMacro;;
      { @selector( MulleScionMethod), @selector( NSCoding) },      // 628c2bf3;MulleScionMethod;b67e77cf;NSCoding
      { @selector( MulleScionMethod), @selector( Printing) },      // 628c2bf3;MulleScionMethod;11e5c20c;Printing
      { @selector( MulleScionMethod), @selector( TraceDescription) },      // 628c2bf3;MulleScionMethod;35e2b50e;TraceDescription
      { @selector( MulleScionMethod), @selector( VariableSubstitution) },      // 628c2bf3;MulleScionMethod;e459bb08;VariableSubstitution
      { @selector( MulleScionMethod), MULLE_OBJC_NO_CATEGORYID },      // 628c2bf3;MulleScionMethod;;
      { @selector( MulleScionMethodCall), MULLE_OBJC_NO_CATEGORYID },      // 3519a2fd;MulleScionMethodCall;;
      { @selector( MulleScionNot), @selector( Printing) },      // 133883ff;MulleScionNot;11e5c20c;Printing
      { @selector( MulleScionNot), @selector( TraceDescription) },      // 133883ff;MulleScionNot;35e2b50e;TraceDescription
      { @selector( MulleScionNot), MULLE_OBJC_NO_CATEGORYID },      // 133883ff;MulleScionNot;;
      { @selector( MulleScionNumber), @selector( Printing) },      // 185dcef1;MulleScionNumber;11e5c20c;Printing
      { @selector( MulleScionNumber), MULLE_OBJC_NO_CATEGORYID },      // 185dcef1;MulleScionNumber;;
      { @selector( MulleScionObject), @selector( BlockExpansion) },      // 7ed9b39e;MulleScionObject;ba0a1bbc;BlockExpansion
      { @selector( MulleScionObject), @selector( NSCoding) },      // 7ed9b39e;MulleScionObject;b67e77cf;NSCoding
      { @selector( MulleScionObject), @selector( Parsing) },      // 7ed9b39e;MulleScionObject;bd0f67fb;Parsing
      { @selector( MulleScionObject), @selector( Printing) },      // 7ed9b39e;MulleScionObject;11e5c20c;Printing
      { @selector( MulleScionObject), @selector( TraceDescription) },      // 7ed9b39e;MulleScionObject;35e2b50e;TraceDescription
      { @selector( MulleScionObject), @selector( VariableSubstitution) },      // 7ed9b39e;MulleScionObject;e459bb08;VariableSubstitution
      { @selector( MulleScionObject), MULLE_OBJC_NO_CATEGORYID },      // 7ed9b39e;MulleScionObject;;
      { @selector( MulleScionOperatorExpression), MULLE_OBJC_NO_CATEGORYID },      // 8ddcf605;MulleScionOperatorExpression;;
      { @selector( MulleScionOr), @selector( Printing) },      // 8ca8d5fd;MulleScionOr;11e5c20c;Printing
      { @selector( MulleScionOr), MULLE_OBJC_NO_CATEGORYID },      // 8ca8d5fd;MulleScionOr;;
      { @selector( MulleScionParameterAssignment), @selector( NSCoding) },      // 4fc4f00b;MulleScionParameterAssignment;b67e77cf;NSCoding
      { @selector( MulleScionParameterAssignment), @selector( Printing) },      // 4fc4f00b;MulleScionParameterAssignment;11e5c20c;Printing
      { @selector( MulleScionParameterAssignment), MULLE_OBJC_NO_CATEGORYID },      // 4fc4f00b;MulleScionParameterAssignment;;
      { @selector( MulleScionParser), @selector( Parsing) },      // 7ef9555b;MulleScionParser;bd0f67fb;Parsing
      { @selector( MulleScionParser), MULLE_OBJC_NO_CATEGORYID },      // 7ef9555b;MulleScionParser;;
      { @selector( MulleScionPipe), @selector( Printing) },      // f868da64;MulleScionPipe;11e5c20c;Printing
      { @selector( MulleScionPipe), @selector( VariableSubstitution) },      // f868da64;MulleScionPipe;e459bb08;VariableSubstitution
      { @selector( MulleScionPipe), MULLE_OBJC_NO_CATEGORYID },      // f868da64;MulleScionPipe;;
      { @selector( MulleScionPlainText), @selector( Printing) },      // 8ab8ca5d;MulleScionPlainText;11e5c20c;Printing
      { @selector( MulleScionPlainText), @selector( TraceDescription) },      // 8ab8ca5d;MulleScionPlainText;35e2b50e;TraceDescription
      { @selector( MulleScionPlainText), MULLE_OBJC_NO_CATEGORYID },      // 8ab8ca5d;MulleScionPlainText;;
      { @selector( MulleScionPrinter), MULLE_OBJC_NO_CATEGORYID },      // 9e80ea61;MulleScionPrinter;;
      { @selector( MulleScionRequires), @selector( NSCoding) },      // 9372a0a9;MulleScionRequires;b67e77cf;NSCoding
      { @selector( MulleScionRequires), @selector( Parsing) },      // 9372a0a9;MulleScionRequires;bd0f67fb;Parsing
      { @selector( MulleScionRequires), @selector( Printing) },      // 9372a0a9;MulleScionRequires;11e5c20c;Printing
      { @selector( MulleScionRequires), MULLE_OBJC_NO_CATEGORYID },      // 9372a0a9;MulleScionRequires;;
      { @selector( MulleScionSelector), @selector( Printing) },      // edc1b27a;MulleScionSelector;11e5c20c;Printing
      { @selector( MulleScionSelector), @selector( TraceDescription) },      // edc1b27a;MulleScionSelector;35e2b50e;TraceDescription
      { @selector( MulleScionSelector), MULLE_OBJC_NO_CATEGORYID },      // edc1b27a;MulleScionSelector;;
      { @selector( MulleScionSet), @selector( Debug) },      // 449b9521;MulleScionSet;a6103382;Debug
      { @selector( MulleScionSet), @selector( NSCoding) },      // 449b9521;MulleScionSet;b67e77cf;NSCoding
      { @selector( MulleScionSet), @selector( Printing) },      // 449b9521;MulleScionSet;11e5c20c;Printing
      { @selector( MulleScionSet), @selector( VariableSubstitution) },      // 449b9521;MulleScionSet;e459bb08;VariableSubstitution
      { @selector( MulleScionSet), MULLE_OBJC_NO_CATEGORYID },      // 449b9521;MulleScionSet;;
      { @selector( MulleScionString), @selector( Printing) },      // 53f4c5bd;MulleScionString;11e5c20c;Printing
      { @selector( MulleScionString), @selector( TraceDescription) },      // 53f4c5bd;MulleScionString;35e2b50e;TraceDescription
      { @selector( MulleScionString), MULLE_OBJC_NO_CATEGORYID },      // 53f4c5bd;MulleScionString;;
      { @selector( MulleScionTemplate), @selector( BlockExpansion) },      // 7edb9c4f;MulleScionTemplate;ba0a1bbc;BlockExpansion
      { @selector( MulleScionTemplate), @selector( Caching) },      // 7edb9c4f;MulleScionTemplate;dc080fe1;Caching
      { @selector( MulleScionTemplate), @selector( CompressedArchive) },      // 7edb9c4f;MulleScionTemplate;077fe2a3;CompressedArchive
      { @selector( MulleScionTemplate), @selector( Convenience) },      // 7edb9c4f;MulleScionTemplate;b6e6b102;Convenience
      { @selector( MulleScionTemplate), @selector( Parsing) },      // 7edb9c4f;MulleScionTemplate;bd0f67fb;Parsing
      { @selector( MulleScionTemplate), @selector( Printing) },      // 7edb9c4f;MulleScionTemplate;11e5c20c;Printing
      { @selector( MulleScionTemplate), @selector( TraceDescription) },      // 7edb9c4f;MulleScionTemplate;35e2b50e;TraceDescription
      { @selector( MulleScionTemplate), MULLE_OBJC_NO_CATEGORYID },      // 7edb9c4f;MulleScionTemplate;;
      { @selector( MulleScionTerminator), @selector( Printing) },      // 60f5faff;MulleScionTerminator;11e5c20c;Printing
      { @selector( MulleScionTerminator), @selector( TraceDescription) },      // 60f5faff;MulleScionTerminator;35e2b50e;TraceDescription
      { @selector( MulleScionTerminator), MULLE_OBJC_NO_CATEGORYID },      // 60f5faff;MulleScionTerminator;;
      { @selector( MulleScionUnaryOperatorExpression), @selector( VariableSubstitution) },      // 64ededbc;MulleScionUnaryOperatorExpression;e459bb08;VariableSubstitution
      { @selector( MulleScionUnaryOperatorExpression), MULLE_OBJC_NO_CATEGORYID },      // 64ededbc;MulleScionUnaryOperatorExpression;;
      { @selector( MulleScionValueObject), @selector( NSCoding) },      // b8ab7406;MulleScionValueObject;b67e77cf;NSCoding
      { @selector( MulleScionValueObject), @selector( TraceDescription) },      // b8ab7406;MulleScionValueObject;35e2b50e;TraceDescription
      { @selector( MulleScionValueObject), MULLE_OBJC_NO_CATEGORYID },      // b8ab7406;MulleScionValueObject;;
      { @selector( MulleScionVariable), @selector( Printing) },      // 5a480a64;MulleScionVariable;11e5c20c;Printing
      { @selector( MulleScionVariable), MULLE_OBJC_NO_CATEGORYID },      // 5a480a64;MulleScionVariable;;
      { @selector( MulleScionWhile), @selector( Printing) },      // 42d36077;MulleScionWhile;11e5c20c;Printing
      { @selector( MulleScionWhile), MULLE_OBJC_NO_CATEGORYID },      // 42d36077;MulleScionWhile;;
      { @selector( NSArray), @selector( TraceValueDescription) },      // 233490fe;NSArray;f69b003f;TraceValueDescription
      { @selector( NSData), @selector( Hoedown) },      // 8fce7861;NSData;fbfc4833;Hoedown
      { @selector( NSData), @selector( StrippedToExamples) },      // 8fce7861;NSData;0ccec34c;StrippedToExamples
      { @selector( NSData), @selector( ZLib) },      // 8fce7861;NSData;18732846;ZLib
      { @selector( NSDate), @selector( MulleScionDescription) },      // cfcedd21;NSDate;04602b46;MulleScionDescription
      { @selector( NSDictionary), @selector( TraceValueDescription) },      // 8b2abcad;NSDictionary;f69b003f;TraceValueDescription
      { @selector( NSFileHandle), @selector( MulleOutputFileHandle) },      // 01a8a865;NSFileHandle;f4e71bf3;MulleOutputFileHandle
      { @selector( NSNull), @selector( ExpressionDescription) },      // f0c42d79;NSNull;1f82ecf6;ExpressionDescription
      { @selector( NSNull), @selector( MulleScionDescription) },      // f0c42d79;NSNull;04602b46;MulleScionDescription
      { @selector( NSNumber), @selector( MulleScionDescription) },      // 8ba34f39;NSNumber;04602b46;MulleScionDescription
      { @selector( NSObject), @selector( ExpressionDescription) },      // b3a66256;NSObject;1f82ecf6;ExpressionDescription
      { @selector( NSObject), @selector( MulleScionComparison) },      // b3a66256;NSObject;49a3663b;MulleScionComparison
      { @selector( NSObject), @selector( MulleScionDataSourceSupport) },      // b3a66256;NSObject;cc20cca6;MulleScionDataSourceSupport
      { @selector( NSObject), @selector( MulleScionDescription) },      // b3a66256;NSObject;04602b46;MulleScionDescription
      { @selector( NSObject), @selector( TraceValueDescription) },      // b3a66256;NSObject;f69b003f;TraceValueDescription
      { @selector( NSString), @selector( GTMNSStringHTMLAdditions) },      // 1994a171;NSString;ae58287f;GTMNSStringHTMLAdditions
      { @selector( NSString), @selector( HTMLEscape) },      // 1994a171;NSString;77864132;HTMLEscape
      { @selector( NSString), @selector( Hoedown) },      // 1994a171;NSString;fbfc4833;Hoedown
      { @selector( NSString), @selector( MulleScionDescription) },      // 1994a171;NSString;04602b46;MulleScionDescription
      { @selector( NSString), @selector( NonExamplesStripped) },      // 1994a171;NSString;fb95d785;NonExamplesStripped
      { @selector( NSString), @selector( TraceValueDescription) },      // 1994a171;NSString;f69b003f;TraceValueDescription
      { @selector( NSValue), @selector( CheatAndHack) },      // 96deaa7d;NSValue;f5730f02;CheatAndHack
      { @selector( _MulleScionNull), @selector( MulleScionDescription) },      // 036e3d07;_MulleScionNull;04602b46;MulleScionDescription
      { @selector( _MulleScionNull), MULLE_OBJC_NO_CATEGORYID },      // 036e3d07;_MulleScionNull;;
